name: build and deploy
on:
  workflow_call:
    secrets:
      service_account:
        required: true
        description: Service account to use for deployment

      registry_org:
        required: true
        description: Registry organization to use for deployment

    inputs:
      image_name:
        type: string
        required: true
        description: Name of the image to deploy

      registry:
        required: false
        type: string
        default: eu.gcr.io
        description: Registry to use for deployment

      tag_type:
        required: false
        type: string
        default: sha
        description: docker-metadata type to use for image tag

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ secrets.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ secrets.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=${{ inputs.tag_type }}
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
