name: Deploy
on:
  workflow_call:
    secrets:
      registry_org:
        required: true
        description: Organization/path to use for deployment

      service_account:
        required: true
        description: Service account to use for deployment

    inputs:
      image_name:
        type: string
        required: true
        description: Name of the image to deploy

      registry:
        required: false
        type: string
        default: eu.gcr.io
        description: Registry to use for deployment

jobs:
  deploy_to_development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: dev.gameflow.tv

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ secrets.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ secrets.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=sha
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy_to_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: stage.gameflow.tv

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ secrets.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ secrets.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy_to_production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: gameflow.tv

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ secrets.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ secrets.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
