name: Deploy
on:
  workflow_call:
    secrets:
      service_account:
        required: true
        description: Service account to use for deployment

    inputs:
      image_name:
        type: string
        required: true
        description: Name of the image to deploy

      registry:
        required: false
        type: string
        default: eu.gcr.io
        description: Registry to use for deployment

      registry_org:
        required: true
        type: string
        description: Registry organization/path to use for deployment

jobs:
  development:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://dev.gameflow.tv

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ inputs.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ inputs.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=sha
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  staging:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://stage.gameflow.tv

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ inputs.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ inputs.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  production:
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://gameflow.tv

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.service_account }}
          project_id: ${{ inputs.registry_org }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ inputs.registry_org }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            suffix=${{ github.sha }}-${{ env.DATES }}

      - name: Deploy to development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
